"""Unit and optional database tests for the temperature forecast package."""

from datetime import datetime, timedelta, timezone
from functools import partial
import math
from pathlib import Path
import tempfile
from types import SimpleNamespace
import unittest

from edgemind.application.forecasts import ForecastService
from edgemind.domain.forecasting import (
    FEATURE_NAMES,
    ForecastError,
    TrainingExample,
    build_training_examples,
    predict_with_payload,
    train_temperature_model,
)
from edgemind.infrastructure.reporting.context import ReportContext
from edgemind.infrastructure.reporting.gateway import FilesystemReportGateway
try:
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from edgemind.infrastructure.persistence.database import Base
    from edgemind.infrastructure.persistence.models import MotorSensorData
    from edgemind.infrastructure.persistence.unit_of_work import (
        SqlAlchemyUnitOfWork,
    )

    HAS_SQLALCHEMY = True
except ModuleNotFoundError:
    HAS_SQLALCHEMY = False



class ForecastingTests(unittest.TestCase):
    """Verify feature pairing, model fitting, and persistence workflows."""

    def setUp(self):
        """Keep generated reports out of the application's runtime directory."""
        self.report_directory = tempfile.TemporaryDirectory()
        context = ReportContext(
            root=Path(self.report_directory.name),
            timezone=timezone.utc,
            anomaly_temperature_threshold=35.0,
        )
        self.forecasts = ForecastService(FilesystemReportGateway(context))

    def tearDown(self):
        """Remove all report artifacts generated by test use cases."""
        self.report_directory.cleanup()

    def test_builds_targets_within_30_minute_tolerance(self):
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        records = [
            SimpleNamespace(
                recorded_at=start + timedelta(minutes=5 * index),
                temperature=25 + index * 0.2,
                humidity=50 + index % 3,
                accel_x=math.sin(index),
                accel_y=math.cos(index),
                accel_z=1 + index * 0.001,
            )
            for index in range(20)
        ]

        examples = build_training_examples(records)

        self.assertEqual(len(examples), 15)
        self.assertTrue(
            all(
                timedelta(minutes=25)
                <= example.target_time - example.source_time
                <= timedelta(minutes=35)
                for example in examples
            )
        )
        self.assertEqual(examples[0].target_temperature, records[6].temperature)

    def test_ridge_model_uses_all_five_features(self):
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        examples = []
        for index in range(40):
            features = (
                20 + index * 0.2,
                45 + (index * 7) % 13,
                math.sin(index * 0.6),
                math.cos(index * 0.4),
                (index % 5) - 2,
            )
            target = (
                4
                + 0.7 * features[0]
                + 0.05 * features[1]
                + 0.8 * features[2]
                - 0.4 * features[3]
                + 0.3 * features[4]
            )
            examples.append(
                TrainingExample(
                    source_time=start + timedelta(minutes=5 * index),
                    target_time=start + timedelta(minutes=5 * index + 30),
                    features=features,
                    target_temperature=target,
                )
            )

        payload = train_temperature_model(examples)
        prediction = predict_with_payload(payload, examples[-1].features)

        self.assertEqual(payload["feature_names"], list(FEATURE_NAMES))
        self.assertLess(payload["mae"], 0.05)
        self.assertIn("r2_score", payload["validation_metrics"])
        self.assertIn("mape_percent", payload["validation_metrics"])
        self.assertAlmostEqual(
            prediction,
            examples[-1].target_temperature,
            delta=0.05,
        )

    def test_validation_purges_training_targets_that_cross_its_origin(self):
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        examples = [
            TrainingExample(
                source_time=start + timedelta(minutes=5 * index),
                target_time=start + timedelta(minutes=5 * index + 30),
                features=(20 + index, 50, 0.1, 0.2, 1.0),
                target_temperature=22 + index,
            )
            for index in range(40)
        ]

        payload = train_temperature_model(examples)

        self.assertEqual(
            payload["validation_strategy"],
            "chronological_tail_with_target_time_purge",
        )
        self.assertEqual(payload["validation_purged_sample_count"], 6)
        self.assertTrue(payload["validation_targets_end_before_validation_sources"])
        self.assertLess(
            datetime.fromisoformat(payload["validation_training_last_target_time"]),
            datetime.fromisoformat(payload["validation_first_source_time"]),
        )

    def test_rejects_insufficient_history(self):
        with self.assertRaises(ForecastError):
            train_temperature_model([])

    @unittest.skipUnless(HAS_SQLALCHEMY, "SQLAlchemy is not installed")
    def test_database_training_and_prediction_round_trip(self):
        engine = create_engine("sqlite:///:memory:")
        Base.metadata.create_all(engine)
        session_factory = sessionmaker(bind=engine)
        session = session_factory()
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        try:
            for index in range(30):
                session.add(
                    MotorSensorData(
                        motor_id="TEST-1",
                        temperature=30 + index * 0.1,
                        humidity=55 + index % 4,
                        accel_x=math.sin(index) * 0.1,
                        accel_y=math.cos(index) * 0.1,
                        accel_z=1 + index * 0.001,
                        vibration=1,
                        status="normal",
                        recorded_at=start + timedelta(minutes=5 * index),
                    )
                )
            session.commit()

            uow_factory = partial(SqlAlchemyUnitOfWork, session_factory)
            with uow_factory() as uow:
                trained = self.forecasts.train(uow, "TEST-1")
            with uow_factory() as uow:
                result = self.forecasts.forecast(
                    uow,
                    "TEST-1",
                    auto_train=False,
                )

            # The final source can pair with a target 25 minutes later because
            # the forecast contract allows a ±5 minute tolerance around 30.
            self.assertEqual(trained["sample_count"], 25)
            self.assertEqual(result["forecast_horizon_minutes"], 30)
            self.assertEqual(
                set(result["features"]),
                set(FEATURE_NAMES),
            )
            self.assertTrue(math.isfinite(result["predicted_temperature"]))
        finally:
            session.close()

    @unittest.skipUnless(HAS_SQLALCHEMY, "SQLAlchemy is not installed")
    def test_uses_training_device_model_for_another_inference_device(self):
        engine = create_engine("sqlite:///:memory:")
        Base.metadata.create_all(engine)
        session_factory = sessionmaker(bind=engine)
        session = session_factory()
        start = datetime(2026, 1, 1, tzinfo=timezone.utc)
        try:
            for index in range(30):
                session.add(
                    MotorSensorData(
                        motor_id="DEMO-1",
                        temperature=30 + index * 0.1,
                        humidity=55 + index % 4,
                        accel_x=math.sin(index) * 0.1,
                        accel_y=math.cos(index) * 0.1,
                        accel_z=1 + index * 0.001,
                        vibration=1,
                        status="training",
                        recorded_at=start + timedelta(minutes=5 * index),
                    )
                )
            session.add(
                MotorSensorData(
                    motor_id="DEMO-2",
                    temperature=32.5,
                    humidity=56,
                    accel_x=0.03,
                    accel_y=-0.02,
                    accel_z=1.01,
                    vibration=1,
                    status="inference",
                    recorded_at=start + timedelta(hours=3),
                )
            )
            session.commit()

            uow_factory = partial(SqlAlchemyUnitOfWork, session_factory)
            with uow_factory() as uow:
                self.forecasts.train(uow, "DEMO-1")
            with uow_factory() as uow:
                result = self.forecasts.forecast(
                    uow,
                    "DEMO-2",
                    auto_train=False,
                    training_motor_id="DEMO-1",
                )

            self.assertEqual(result["motor_id"], "DEMO-2")
            self.assertEqual(result["inference_motor_id"], "DEMO-2")
            self.assertEqual(result["training_motor_id"], "DEMO-1")
            self.assertEqual(result["model"]["training_motor_id"], "DEMO-1")
            self.assertEqual(result["features"]["temperature"], 32.5)
            self.assertTrue(math.isfinite(result["predicted_temperature"]))
        finally:
            session.close()


if __name__ == "__main__":
    unittest.main()
